### ISSUE TITLE
Counties are no longer current

### ISSUE THREAD

**Issue by Prooffreader** [Deleetdk/USA.county.data#1]
There have been two changes to U.S. Counties in 2015:

Shannon County, South Dakota, fips 46113
is now Oglala Lakota County, fips 46102

Bedford city, Virginia county, fips 51515 has now been merged with Bedford County, fips 51019.

**Comment by Deleetdk** [comment]
Sigh!

**Comment by Prooffreader** [comment]
It's even worse in Canada, where we don't have anything like counties. So we have to use Postal Code (like zip code), except there are over 80,000 of them, and every month there are new ones, retired ones, ones that change shape, ones that get amalgamated... at the company I work for it's literally 1/4 of a full-time job just to handle the GIS issues of Canada Post postal code geography changes.

**Comment by Deleetdk** [comment]
I think we will just merge the mergeable ones here and then call it a day. If it's only a very few unimportant errors out of ~3100 datapoints, then I have other things to use my time on.
